# Generated by Django 3.2.6 on 2022-03-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_twentym'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalTwenty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('session', models.CharField(max_length=50)),
            ],
        ),
    ]
