# Generated by Django 3.2.6 on 2022-03-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_intervaltwenty'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervaltwenty',
            name='name',
            field=models.CharField(default='50', max_length=50),
        ),
        migrations.AddField(
            model_name='intervaltwenty',
            name='reached',
            field=models.BooleanField(default=False),
        ),
    ]
