# Generated by Django 3.2.6 on 2022-03-24 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20220324_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervalTwenty2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='50', max_length=50)),
                ('start_time', models.TimeField(auto_now_add=True)),
                ('session', models.CharField(max_length=50)),
                ('reached', models.BooleanField(default=False)),
            ],
        ),
    ]
