# Generated by Django 3.2.6 on 2022-03-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_intervaltwenty2_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fourhours',
        ),
        migrations.DeleteModel(
            name='Sixhours',
        ),
        migrations.DeleteModel(
            name='Twohours',
        ),
    ]
