# Generated by Django 4.0.2 on 2022-06-10 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20220324_2009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TwentyM',
            new_name='TM_INTERVAL',
        ),
    ]
