# Generated by Django 4.0.2 on 2022-06-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_tm_interval_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='totp',
            name='barcode',
            field=models.ImageField(blank=True, null=True, upload_to='barcodeImages'),
        ),
    ]
